TRUNCATE TABLE PUBLICACIONES;
TRUNCATE TABLE PREGUNTAS_ESTABLECIDAS;
TRUNCATE TABLE PREGUNTAS;
TRUNCATE TABLE USUARIOS;

DROP TABLE PREGUNTAS;
DROP TABLE USUARIOS;


SELECT * FROM PREGUNTAS;
SELECT * FROM PUBLICACIONES;
SELECT * FROM USUARIOS;